version: 0.0
os: linux
files:             
  - source: ./BookStoreApp/target/BookStoreApp-1.0-SNAPSHOT.war
    destination: /var/lib/tomcat9/webapps
hooks:
  ApplicationStop:
    - location: ./applicationStop.sh
      timeout: 180
      runas: ubuntu
  BeforeInstall:
    - location: ./beforeInstall.sh
      timeout: 180
      runas: ubuntu
  AfterInstall:
   - location: ./afterInstall.sh
     timeout: 180
     runas: ubuntu
  ApplicationStart:
    - location: ./applicationStart.sh
      timeout: 180
      runas: ubuntu
