version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:

      - checkout
      
      - run:
          name: Build WAR
          command: |
            ls -al
            cd BookStoreApp/
            ls -al
            mvn clean install
            cd target
            ls -al
            cd ../../
            ls -al




